name: CI SNAPSHOT

on:
  workflow_dispatch:

  push:
    branches:
      - '*.x'

concurrency:
  group: group-snapshot-for-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-snapshot:
    uses: spring-io/spring-github-workflows/.github/workflows/spring-artifactory-gradle-snapshot.yml@main
    with:
      artifactoryUrl: https://repo.spring.vmware.com
      targetRepository: spring-commercial-snapshot-local
      artifactoryProjectKey: spring
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}
