name: CI SNAPSHOT

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - '*.x'

concurrency:
  group: group-snapshot-for-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-snapshot:
    uses: spring-io/spring-github-workflows/.github/workflows/spring-artifactory-gradle-snapshot.yml@main
    secrets:
      GRADLE_ENTERPRISE_SECRET_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}