name: Pull Request Build

on:
  pull_request:
    branches:
      - '*.x'

jobs:
  build-pull-request:
    uses: spring-io/spring-github-workflows/.github/workflows/spring-gradle-pull-request-build.yml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.COMMERCIAL_ARTIFACTORY_RO_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.COMMERCIAL_ARTIFACTORY_RO_PASSWORD }}
